### ISSUE TITLE
Addition of color dots

### ISSUE THREAD

**Issue by Ribster** [hubmartin/ESP8266_WS2812B_UDP#1]
Hey @hubmartin , I used your project for my christmas tree using the ESP-01.
I've changed the dots animation a little bit.
Try it out, and let me know what you think!

```
void dotsDraw()
{
  loadPixels();
  
  for (int pixelCount = 0; pixelCount < width; pixelCount++)
  {                    
    float b = blue(pixels[pixelCount]);
    float r = red(pixels[pixelCount]);
    float g = green(pixels[pixelCount]);
    b -= b * 0.001;
    r -= r * 0.001;
    g -= g * 0.001;
    
    pixels[pixelCount] =  color(r,g,b);
  }

  
  int gSize = (int)random(2,10);
  
  int canDraw = (int)random(0,5);
  if((canDraw & 1) == 1)
  {
    int r = (int)random(0,width);
    color c = color((int)random(0,255),(int)random(0,255),(int)random(0,255));
    for(int i = r - gSize; i < r + gSize; i++)
    {
     if(i >= 0 && i < width)
     {
       //color c = color(255,210,20);
       
       //color c = color(100,227,127);
       color b = pixels[i]; //color(0,0,0); 
       //color b = color(0,255,0);
       
       pixels[i] =  lerpColor(c, b, map(abs(i - r), 0, gSize, 0, 1));
       
     }
    }
  }
  
  updatePixels();
  
  for(int x = 0; x < width; x++)
  {
    stroke(pixels[x]);
    line(x,1,x,height);
  }
  
  
}
```

**Comment by hubmartin** [comment]
Hi Ribster,
thanks a lot for your contribution. The effect looks amazing. I've added it and pushed to the git with your name, let me know if it is ok with you. 
Honestly I haven't much time to fiddle with effects. I used Processing few years ago and now I thought that it would be simple program to render the effects.
Today I wanted add some colour effect for Christmas day but I don't have to now :)
I would need to clean a code a little bit and also put configuration aside. I wasn't expecting anyone contributing to this project so soon.

Specially this code which is "stretching" the computed dots to lines is slowing code a lot on my Rpi2 so I put it everytime away, but it is not pushed right now.

Are you on Twitter? I would put a tweet about this improvement.

Have a nice holiday!

**Comment by Ribster** [comment]
Hey Hub,

Normally i should fork it and add it to a new scene.
But that meant adding a new dots file and i was not sure if you wanted help ;).
Yep, no problem with my name added.

Yeah, i'm writing a linux kernel driver at the moment, and this was a nice project in between to fiddle with.
That's why i used your project after i watched your video.
Clean, simple, doesn't need more :).
I'm planning on running it also on a rPi, currently it's running only on my macbook.

Personally i'm new to processing, but i like the way you handled it.
I had a look at the animations on the processing page, and i think adding a plugin for GIF files would be nice.
Screen capture is also very nice. You can have a look at [http://www.solderlab.de/index.php/software/glediator](url), they do it very nicely..

Then i'm glad i shared it with you :). Thanks for the project, it helped me a lot.
I blowed 3 ESP8266's GPIO to the WS2812.. Quite ashame, but the 5V logic is to blame i guess..

I like the stretch. But i was thinking of a lot more animations, like a 'comet' animation and stuff..

Yep i'm on twitter, i'm @RobbeVA there.

Have a nice holiday too.
I'll keep in touch if i have something more to add!
